# Generated by Django 6.0.3 on 2026-04-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_payment_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
